### ISSUE TITLE
有没有办法支持 通过parentId 构建的层次数据？

### ISSUE THREAD

**Issue by cuiliang** [1inus/ng.tree#3]
控件写的很不错！
希望可以支持parentId方式，这样就能直接从数据库读出来加载到界面上了。

**Comment by 1inus** [comment]
您说的可能是onFold方法：
`onFold? : (node?:any) => boolean;,execute before treenode collapse or uncollapse, returns false to`

这个方法的作用是：节点被展开和关闭时调用，传入当前被展开的节点对象，如果返回值为false，则不展开或者不关闭。

您可以获得node对象的id然后去加载数据，数据加载完毕后为该节点动态生成children就可以了

**Comment by cuiliang** [comment]
好的，谢谢~
